// 공유 도구/강점/기술 데이터 (홈·내비·푸터에서 사용)
export const TOOLS = [
  {
    idx: "01",
    href: "/recommend",
    nav: "상황추천",
    en: "RECOMMEND",
    title: "상황 기반 추천",
    desc: "자연어로 상황을 말하면 AI가 키워드를 뽑아 맥락에 맞는 상품을 추천합니다.",
    chips: ["자연어 입력", "키워드 추출", "네이버 쇼핑"],
  },
  {
    idx: "02",
    href: "/compare",
    nav: "비교판단",
    en: "COMPARE",
    title: "비교 · 구매 판단",
    desc: "여러 상품을 나란히 비교해 무엇을 살지 판단을 돕습니다.",
    chips: ["스펙 비교", "가격", "구매 판단"],
  },
  {
    idx: "03",
    href: "/review",
    nav: "리뷰분석",
    en: "REVIEW",
    title: "리뷰 요약 · 장단점",
    desc: "흩어진 리뷰에서 장단점과 구매 추천 여부를 요약합니다.",
    chips: ["장단점", "요약", "추천 여부"],
  },
  {
    idx: "04",
    href: "/curation",
    nav: "큐레이션",
    en: "CURATION",
    title: "라이프스타일 큐레이션",
    desc: "여행·계절·테마로 어울리는 쇼핑 리스트를 큐레이션합니다.",
    chips: ["테마", "시즌", "여행"],
  },
  {
    idx: "05",
    href: "/sourcing",
    nav: "소싱",
    en: "SOURCING",
    title: "소싱 아이디어",
    desc: "셀러를 위한 상품 소싱 아이디어와 시장 신호를 제안합니다.",
    chips: ["시장 신호", "셀러", "아이디어"],
  },
  {
    idx: "06",
    href: "/links",
    nav: "링크관리",
    en: "LINKS",
    title: "쿠팡/자사몰 링크 관리",
    desc: "쿠팡·자사몰 상품 URL을 저장하고 제목·이미지를 보강해 태그로 관리합니다.",
    chips: ["URL 저장", "OG 보강", "태그"],
  },
  {
    idx: "07",
    href: "/dashboard",
    nav: "대시보드",
    en: "DASHBOARD",
    title: "고객 니즈 대시보드",
    desc: "대화 로그를 분석해 고객 니즈와 기회를 시각화합니다.",
    chips: ["니즈 분석", "시각화", "로그"],
  },
  {
    idx: "08",
    href: "/widget-demo",
    nav: "위젯",
    en: "WIDGET",
    title: "고객 응대 위젯",
    desc: "한 줄 스크립트로 어떤 쇼핑몰에도 챗봇을 삽입합니다.",
    chips: ["임베드", "1줄 스크립트", "챗봇"],
  },
];

export const STRENGTHS = [
  { idx: "01", title: "자연어 한 줄로 작동", desc: "상황만 말하면 키워드 추출부터 검색, 정리까지 에이전트가 알아서 수행합니다." },
  { idx: "02", title: "네이버 쇼핑 실시간 연동", desc: "실제 판매 중인 상품과 가격을 그대로 가져와 추천과 비교에 사용합니다." },
  { idx: "03", title: "일관된 구조화 결과", desc: "요약·장단점·키워드를 항상 같은 형식으로 정리해 바로 활용할 수 있습니다." },
  { idx: "04", title: "어디든 임베드", desc: "한 줄 스크립트로 기존 쇼핑몰에 고객 응대 위젯을 손쉽게 삽입합니다." },
];

export const TECH_TOKENS = [
  "NAVER 쇼핑 API",
  "OpenAI",
  "gpt-4o-mini",
  "실시간 검색",
  "키워드 추출",
  "리뷰 분석",
  "데이터 구조화",
  "위젯 임베드",
];
